### ISSUE TITLE
Debugger is not working

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-mono-debug#1]
_From @wtang3 on November 20, 2015 3:16_

Getting error when running app in debug mode.

When hitting play on debugger, debugger options appear for split second and exception occurs.

error while processing request '{_request}' (exception: {_exception})

![screen shot 2015-11-19 at 10 09 28 pm](https://cloud.githubusercontent.com/assets/3191584/11291059/57dd9988-8f0a-11e5-9a1b-1b5804581e54.png)

OS: Mac

_Copied from original issue: Microsoft/vscode#306_

**Comment by weinand** [comment]
The problem with the unreadable error message has been fixed through PR #4

**Comment by wtang3** [comment]
Thank you very much weinand!

**Comment by amansingh36** [comment]
@weinand, I'm also getting the same error. How we can solve this?

**Comment by amansingh36** [comment]
@mbcrump, I'm getting the same error. How we can solve this?

**Comment by weinand** [comment]
@amansingh36 I have created a new [release](https://github.com/Microsoft/vscode-mono-debug/releases/tag/0.10.2) of the mono-debug adapter that should fix the problem with the unreadable error message. Please give it a try and let me know what the real error is.
A 'how-to install vsix extensions' can be found [here](https://code.visualstudio.com/docs/extensions/install-extension).

**Comment by amansingh36** [comment]
@weinand, Thanks for the reply. I've installed your extension via below method still receiving error.

INSTALL METHOD:
"You can also install a .vsix by opening the file from within VS Code. Run File | Open File... or unassigned and select the extension .vsix."

ERROR:
error while processing request '{_request}' (exception: {_exception})

Please help. Thanks

**Comment by amansingh36** [comment]
@weinand, I'm trying new method which will load the extension every time when Visual Studio Code will run. But the problem is I don't know where the ".vscode/extensions" folder is located on Mac.

NEW METHOD TRYING:
If you want to load your extension or customization each time VS Code runs, copy your project to a new folder under .vscode/extensions.
    $HOME/.vscode/extensions/myextension

**Comment by amansingh36** [comment]
@weinand, tried both ways to install but didn't helped. I also found one error in OUTPUT window:

[ERROR:OmniSharp.Dnx.DnxPaths] The specified runtime path 'default' does not exist. Searched locations

**Comment by amansingh36** [comment]
@weinand, Everything sorted except ERROR:
error while processing request '{_request}' (exception: {_exception})

**Comment by weinand** [comment]
my pre-release version 0.10.2 of mono-debug had the wrong publisher, so you are still seeing the original mono-debug. Could you please try it again with this [release 0.10.3](https://github.com/Microsoft/vscode-mono-debug/releases/tag/0.10.3).

First install the previous mono-debug extension by
* pressing F1
* type "ext"
* select "Show Installed Extensions"
* pick "mono-debug 0.10.2"
* click the "X" on the right of the entry to delete it.
* let VS Code restart

Then install 0.10.3 mono-debug by opening it via VS Code open action.

**Comment by amansingh36** [comment]
Where is .vsix file? Because I don't know how to install via source.

**Comment by weinand** [comment]
Sorry, I forgot to attach it...

**Comment by amansingh36** [comment]
@weinand, Thanks for the support. But still receiving error:
"error while processing request 'launch' (exception: The best overloaded method match for `OpenDebug.Terminal.LaunchInTerminal(string, string, string[], string, string[], System.Collections.Generic.Dictionary<string,string>)' has some invalid arguments)"

**Comment by amansingh36** [comment]
@weinand, Thanks for the support. But now receiving another error:
"error while processing request 'launch' (exception: The best overloaded method match for `OpenDebug.Terminal.LaunchInTerminal(string, string, string[], string, string[], System.Collections.Generic.Dictionary<string,string>)' has some invalid arguments)"

**Comment by weinand** [comment]
yes, as I said above, I first had to fix the problem with the unreadable error message. Now, that we can see the real error message, I will reopen this bug and work on the fix. Thanks for helping me with this.

**Comment by weinand** [comment]
@amansingh36 what version of mono do you have installed on your OS X?

**Comment by amansingh36** [comment]
The latest Mono release: 4.2 Stable (4.2.1.102)

**Comment by amansingh36** [comment]
The latest Mono release: 4.2 Stable (4.2.1.102)

Mono for Mac OS X Universal (32 & 64 bit) preview
This package contains both 32 and 64-bit Mono for OS X.

**Comment by weinand** [comment]
@amansingh36 I think I know what the problem is. Could you please remove the environment variables (the "env": [...])  in your launch config and see whether that makes a difference?

**Comment by amansingh36** [comment]
@weinand, If I remove "env": { }" still receiving error:

error while processing request 'launch' (exception: The best overloaded method match for `OpenDebug.Terminal.LaunchInTerminal(string, string, string[], string, string[], System.Collections.Generic.Dictionary<string,string>)' has some invalid arguments)

**Comment by weinand** [comment]
@amansingh36 Could you please try [this release](https://github.com/Microsoft/vscode-mono-debug/releases/tag/0.10.4).

**Comment by amansingh36** [comment]
@weinand Everything working perfectly fine now. Thanks

I've an idea shall we write an article together on Visual Studio Code for Setup to Use (End to End). Will you help?

**Comment by amansingh36** [comment]
@weinand, Everything working perfectly fine now. Thanks for your help.

I've an idea shall we write an article together on Visual Studio Code for Setup to Use (End to End). Will you help?

**Comment by amansingh36** [comment]
@weinand, Everything worked perfectly fine with your latest release - 0.10.4. Thanks for your help and prompt replies.

I've a personal request for you, will you be interested to spare some time from your busy schedule and become an author on Visual Studio Code, Visual Studio, etc. at Asian Fox Developments, Blog (Worldwide) www.asianfoxdevelopments.com.

I will be obliged. Thanks

**Comment by amansingh36** [comment]
@weinand, I've a personal request for you, will you be interested to spare some time from your busy schedule and become an author on Visual Studio Code, Visual Studio, etc. at Asian Fox Developments, Blog (Worldwide) www.asianfoxdevelopments.com.

I will be obliged. Thanks

Aman Singh
Senior .NET Dev.
Technical Department
Asian Fox Developments
